name: Install Flutter project
description: |
  This action will install a Flutter project together with the required
  Flutter environment
inputs:
  flutter-version:
    description: Flutter version to use
    required: true
  flutter-architecture:
    description: 'The architecture of Flutter SDK executable (x64 or arm64)'
    required: false
    default: '${{ runner.arch }}'
  setup-java:
    description: Defines if the Java environment should be set up
    required: false
    default: 'true'
  java-version:
    description: Java version used (applicable only when setup-java is true)
    required: false
    default: '17'
  install:
    description: Set to false if you want to skip the automatic project package installation
    required: false
    default: 'true'
  enforce-lockfile:
    description: Enforce pubspec.lock (if install is true). Fail resolution if pubspec.lock does not satisfy pubspec.yaml
    required: false
    default: 'true'
  git-ssh-key:
    description: If set, an ssh-agent will be setup with this private SSH key
    required: false
    default: ''
  cloudsmith-api-key:
    description: If set, authenticate agains Clousmith private packages repository
    required: false
    default: ''
  cache-flutter:
    description: Cache the Flutter SDK and .pub-cache content
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup Java environment
      uses: actions/setup-java@v2
      if: ${{ inputs.setup-java == 'true' }}
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
    - name: Install flutter environment
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ inputs.flutter-version }}
        architecture: ${{ inputs.flutter-architecture }}
        channel: stable
        cache: ${{ inputs.cache-flutter }}
    - name: Set-up ssh-agent
      uses: webfactory/ssh-agent@fd34b8dee206fe74b288a5e61bc95fba2f1911eb
      if: ${{ inputs.git-ssh-key != '' }}
      with:
        ssh-private-key: ${{ inputs.git-ssh-key }}
    - name: Authenticate against private packages repository
      if: ${{ inputs.cloudsmith-api-key != '' }}
      shell: bash
      run: echo ${{ inputs.cloudsmith-api-key  }} | flutter pub token add https://dart.cloudsmith.io/dronetag/software/
    - name: Get project dependencies
      shell: bash
      run: flutter pub get ${{ (inputs.enforce-lockfile == 'true' && '--enforce-lockfile') || ''}}
      if: ${{ inputs.install == 'true' }}
