name: Create a release on Sentry

# This workflows creates a new release on Sentry
#
# This is effectively just letting Sentry know that this version
# might appear in the future error reports (nothing happens if they don't).

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      url:
        required: true
      auth-token:
        required: true
      organization:
        required: true
      project:
        required: true


jobs:
  create-sentry-release:
    name: Create release on Sentry
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository (full-depth)
        uses: actions/checkout@v2
        with: { fetch-depth: 0 } # Required for auto-commits
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: ${{ secrets.url }}
          SENTRY_AUTH_TOKEN: ${{ secrets.auth-token }}
          SENTRY_ORG: ${{ secrets.organization }}
          SENTRY_PROJECT: ${{ secrets.project }}
        with:
          version: ${{ inputs.version }}
          ignore_missing: true
          ignore_empty: true